name = "REPL"
defaultTargets = ["repl"]

[[lean_lib]]
name = "REPL"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.18.0-rc1"

[[lean_exe]]
name = "repl"
root = "REPL.Main"
supportInterpreter = true
